site_name: Coyote Documentation
theme: bootstrap
repo_url: https://github.com/kotarotanahashi/coyote
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

pages:
- Home: index.md
- Core:
    - 'Model': 'core/model.md'
- Layer:
    - 'FullyConnect': 'layer/FullyConnect.md'
    - 'Logistic Regression': 'layer/LogisticRegression.md'
- Examples:
    - 'MNIST': 'examples/mnist.md'
- MarkDown: markdown.md


