site_name: Cerf Documentation
theme: readthedocs
repo_url: https://github.com/kotarotanahashi/cerf
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML']

pages:
- Home: index.md
- Core:
    - 'Model': 'core/model.md'
- Layer:
    - 'FullyConnect': 'layer/FullyConnect.md'
    - 'Logistic Regression': 'layer/LogisticRegression.md'
- MarkDown: markdown.md


